### PR TITLE
added zoom level for OSMAND on iOS

### PR DESCRIPTION
**Pull request by bridystone**
zoom level is available in OSMAND for iOS.

added z parameter for OSMAND on iOS enables zoom for showMarker

### CODE REVIEW

**Comment by mattermoran** [comment]
I wonder why I haven't added it before. Assume the support for it was added after that. How about the title? Maybe ios also supports that now?

**Comment by mattermoran** [comment]
Merging this now and will check if title is supported

**Comment by bridystone** [comment]
According to your documentation title is available "only" for iOS - and not for Android.
I can confirm that iOS properly presents this as title.

however on Android it is yet excluded as parameter - maybe it would also work if added

**Comment by bridystone** [comment]
I've checked the title - it's *not* working on Android - at least for me ;)

**Comment by mattermoran** [comment]
Yeah, I looked in the wrong place and mistakenly thought ios didn't support both zoom and title but apparently, android was missing the title. Well, I guess it still doesn't work on Android, nothing we can do about that :)
Thanks for confirming that! :)

**Pull request merged**
