### PR TITLE
fix null origin

### PR DESCRIPTION
**Pull request by denizz311**
if origin is NULL (for example disabled geolocation on device) google maps will find some object on map with name which contains NULL in title and think that this is an origin

### CODE REVIEW

**Comment by mattermoran** [comment]
Hi! Thanks for your contribution!
When you say the issue is present in google maps do you actually mean apple maps instead? The part of the code you fixed is only being used by apple maps

**Comment by mattermoran** [comment]
Hmm I don't think you mean apple maps as I do check if the origin is null or not in this code:
image

I think I see that the problem might occur in google maps if e.g you pass something like origin: Coords(null, null) because I currently only check if the origin itself is null and not the contents of it. The solution to that would probably be adding support for array in `Utils.nullOrValue` so that it could either take a single value as it is now like `Utils.nullOrValue(origin, '')` or a list like `Utils.nullOrValue([origin?.latitude, origin?.longitude], '')` and if any of the values in array null then return null. That would technically fix it. 
If you would like to implement that then please do or if you have better ideas let me know I'd be happy to discuss :)

**Comment by denizz311** [comment]
> Hi! Thanks for your contribution!
> When you say the issue is present in google maps do you actually mean apple maps instead? The part of the code you fixed is only being used by apple maps

not really. in maps from Google it is also used origin https://stackoverflow.com/a/51114029/12893167

**Comment by ITmxs** [comment]
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:map_launcher/map_launcher.dart';

class MapsSheet {
  BuildContext context;
  Function(AvailableMap map) onMapTap;
  MapsSheet({this.context, this.onMapTap});

  void show() async {
    List<AvailableMap> availableMaps = await MapLauncher.installedMaps;
    for (var map in availableMaps) {
      map.mapName = getLocalName(amap: map);
    }

    showModalBottomSheet(
      // backgroundColor: Colors.transparent,
      context: context,

      builder: (BuildContext context) {
        return Container(
          padding: EdgeInsets.only(left: 10),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.all(Radius.circular(20)),
          ),
          height: 400,
          child: Column(
            children: <Widget>[
              Expanded(
                child: SingleChildScrollView(
                  child: Container(
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.all(Radius.circular(16)),
                    ),
                    child: Wrap(
                      children: <Widget>[
                        for (var map in availableMaps)
                          ListTile(
                            onTap: () => onMapTap(map),
                            title: Text(map.mapName),
                            leading: SvgPicture.asset(
                              map.icon,
                              height: 30.0,
                              width: 30.0,
                            ),
                          ),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  String getLocalName({AvailableMap amap}) {
    switch (amap.mapType) {
      case MapType.amap:
        return '高德地图';

      case MapType.baidu:
        return '百度地图';
      case MapType.tencent:
        return '腾讯地图';
      case MapType.google:
        return '谷歌地图';

      default:
        return amap.mapName;
    }
  }
}

**Comment by mattermoran** [comment]
The `origin` is actually optional which means code like 
```dart
googleMap.showDirections(
...,
origin: null,
)
```

will produce url `https://www.google.com/maps/dir/?api=1&destination=37.759392,-122.5107336&travelmode=driving`

the `origin` will not be a part of the url.

**Pull request closed without merging**
