### PR TITLE
Added Flitsmeister

### PR DESCRIPTION
**Pull request by robinbonnes**
This PR adds support for the Flitsmeister app.

### CODE REVIEW

**Comment by frankvollebregt** [comment]
Hi! I'm also interested in support for FM as well as Truckmeister, the truck variant. 

https://github.com/frankvollebregt/map_launcher/tree/flitsmeister-truckmeister

In my own fork of this repository, I added your commits and added Truckmeister as well, but it seems like while the correct app launches on iOS, it does not correctly parse the coordinates. Have you experienced this as well with your own Flitsmeister integration?

**Comment by frankvollebregt** [comment]
I just heard back from Flitsmeister, and they stated the following:
1. iOS support for passing a location is not available and not currently planned
2. Android support happens to work, but was never built into the app consciously

For now, we can set these packages as "Android only" and proceed with merging. @robinbonnes can you take a look at my PR over in your fork?

Otherwise, I'll create my own PR with your commits instead.

**Comment by mattermoran** [comment]
@frankvollebregt can you create a new pr with those and your changes? I'll make sure to mention both of you in the changelog

**Comment by robinbonnes** [comment]
Hey Frank,
Thanks for also adding Truckmeister! I've just merged your PR, ofcourse you are always free to make your own PR.

**Comment by mattermoran** [comment]
hey @robinbonnes  
that's awesome, could you then also make sure there's no merge conflicts?
then I can merge this pr

**Comment by robinbonnes** [comment]
Hey @mattermoran,

I've just fixed those.

**Comment by frankvollebregt** [comment]
We should clearly tell that iOS is not supported for these two (at the time). We can open the app, but can't start navigation

**Comment by mattermoran** [comment]
@robinbonnes fantastic, thanks!

@frankvollebregt if it can only open the app itself on iOS I think it's pretty useless and we can just remove support for it and make it android only (just like some other maps)

Will clean up tomorrow and make a release.

**Comment by mattermoran** [comment]
Well it was a very long tomorrow but it is now available in v3 :)

**Pull request merged**
