### PR TITLE
Upgrade flutter_svg

### PR DESCRIPTION
**Pull request by tuarrep**

### CODE REVIEW

**Comment by mattermoran** [comment]
We can't really upgrade flutter_svg to 0.18 at the moment as it requires flutter version >=1.18 but current stable is 1.17
Will have to wait for new stable release

**Comment by tuarrep** [comment]
Good point. I'm on beta because of specific needs. I haven't noticed the
requirements.

It'll be ready for the moment of Flutter 1.18 release :)

**Comment by jcsena** [comment]
I think that you could modify the pull request by `">=0.17.4"` instead of `^0.17.4`

**Comment by tuarrep** [comment]
Yes. But when constraint was introduced (56bfa80d2370287a52951be67f51a0d45d161ff4) it was by using `^`.

Is there any objections to use `>=` @mattermoran

**Comment by jcsena** [comment]
Let me explain the versioning:

`^0.17.0` is the same as `">=0.17.0 <0.18.0"` for that reason you can't install the new version of `flutter_svg`.

But, if you use `">=0.17.0"` you could support version `0.17.0` and `0.18.0` 

@mattermoran @tuarrep 
More info: [caret-syntax](https://dart.dev/tools/pub/dependencies#caret-syntax)

**Comment by mattermoran** [comment]
Hey @jcsena thanks for explaining. For some reason I was under assumption that caret syntax allows all the versions in the major range like e.g `^0.17.0` is `">=0.17.0 <1.0.0"` but looks like it only works like that after version 1.0.0
In that case we can use `">=0.17.0"` to support both versions. I haven't really tested on branches other than stable but I assume it works for you guys so it should be fine then.
@tuarrep feel free to update the constraints

**Comment by tuarrep** [comment]
Just done

**Comment by mattermoran** [comment]
Awesome, thanks

**Comment by mattermoran** [comment]
@tuarrep @jcsena version 0.8.2 with this change is available on pub now. I also added upper bound `<1.0.0` in case there's some breaking change and because pub complains when no upper bound specified.
Thanks!

**Comment by jcsena** [comment]
@mattermoran thanks a lot and thanks for you great project!

**Pull request merged**
