### PR TITLE
Feature/mapy cz

### PR DESCRIPTION
**Pull request by TheHumr**

### CODE REVIEW

**Comment by 12people** [comment]
It's not working on Android because `<package android:name="cz.seznam.mapy" />` is missing from `AndroidManifest.xml`.

**Comment by mattermoran** [comment]
I don't know if it even works with that thing added in manifest. I checked the docs and it says url coords should be in the `q` param but here it's in the `id`

**Comment by mattermoran** [comment]
@TheHumr could you provide a video of it working on android and ios?
also the docs say it does support the google-maps-like urls for direction which is not implemented

**Comment by 12people** [comment]
> I don't know if it even works with that thing added in manifest. I checked the docs and it says url coords should be in the `q` param but here it's in the `id`

It worked for me — at least, the directions link I tried worked. (Though only linking to the place and not to directions, as the API says that there's no straightforward way to build direction links.)

That said, if the docs recommend another type of linking, the code should probably be adjusted for that.

**Comment by mattermoran** [comment]
The docs say it supports google urls for marker and navigation I wonder if we can just use the existing google format and just trigger mapycz intent
image

**Comment by mattermoran** [comment]
I'm going to give it a go

**Comment by mattermoran** [comment]
Well nevermind, seems like current approach is probably best. Their docs suck, even the examples they themself provide don't work
```
No Activity found to handle Intent { act=android.intent.action.VIEW dat=http://maps.google.com/... flg=0x10000000 pkg=cz.seznam.mapy }, null, android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=http://maps.google.com/... flg=0x10000000 pkg=cz.seznam.mapy }
```

I tested on both android and ios and it seems to be working. 

I'll get this merged

**Comment by mattermoran** [comment]
Published 3.2.0 with those changes. 

Thanks @TheHumr

**Pull request merged**
