### PR TITLE
Petal Maps added.

### PR DESCRIPTION
**Pull request by mericgerceker**
Hi, I added the petal map. Please check :)

### CODE REVIEW

**Comment by mattermoran** [comment]
Hey, awesome, let me test that, and if all is good I will release :)

**Comment by mericgerceker** [comment]
Hello, when can you publish the update on Pub.Dev? We want to release our application to the Huawei market as soon as possible :)

**Comment by mattermoran** [comment]
Will do within an hour

**Comment by mattermoran** [comment]
@mericgerceker uploaded version 2.2.0 with your changes :)

**Comment by mattermoran** [comment]
@mericgerceker released 2.2.1 with updated petal maps icon :)

**Comment by mericgerceker** [comment]
Thank you so much :)

**Pull request merged**
