### PR TITLE
Support added for MAPPLS MapmyIndia

### PR DESCRIPTION
**Pull request by Ajaay7**
Support added for MAPPLS MapmyIndia

### CODE REVIEW

**Comment by mattermoran** [comment]
Heya. Seems like there's already a PR for this map here https://github.com/mattermoran/map_launcher/pull/166 but could you please provide video recording of it working for both showing marker and directions on android and ios as I can't test it myself?

**Comment by Ajaay7** [comment]
https://github.com/user-attachments/assets/7ae11260-cfce-4879-9e0f-41e412f8d04b


https://github.com/user-attachments/assets/7613f0bf-a927-4cad-9b94-f8af20e2b066

Android

**Comment by Ajaay7** [comment]
https://github.com/user-attachments/assets/4e4fbe4e-20f5-4606-9508-c29608a0f976


https://github.com/user-attachments/assets/6d20baa0-79ef-4420-b283-a729c5a1515a

iOS

**Comment by Ajaay7** [comment]
Hi, @mattermoran ,did you see the recording.

**Comment by mattermoran** [comment]
> Hi, @mattermoran ,did you see the recording.

Hey @Ajaay7 cheers looks great. 
I'll merge this pr and make a release soon but given that https://github.com/mattermoran/map_launcher/pull/166 was submitted earlier and nearly identical but a bit more diffy I'll just credit you both in release notes if you don't mind

**Comment by Ajaay7** [comment]
> > Hi, @mattermoran ,did you see the recording.
> 
> Hey @Ajaay7 cheers looks great. I'll merge this pr and make a release soon but given that #166 was submitted earlier and nearly identical but a bit more diffy I'll just credit you both in release notes if you don't mind

Sure no issues.

**Comment by mattermoran** [comment]
by the way before I release isn't mappls more commonly used name? I mean website seems to be mappls and instagram etc. 
so doesn't it make sense instead of mmi use mappls? I have no idea just don't want to make breaking change later

**Comment by Ajaay7** [comment]
Yes you are correct MAPPLS is mostly used now, but most applications already know the name map my India. So, I see it won't be a big issue.

**Comment by mattermoran** [comment]
yeah but my problem is that `mmi` may not be very descriptive and recognizable compared to `mappls`. wouldnt you think it might be better to use `mappls` instead?

**Comment by Ajaay7** [comment]
yes mappls seems to be better, I will change to mappls and push now?

**Comment by mattermoran** [comment]
no need I can do it. cheers

**Pull request merged**
