### PR TITLE
chore: update waze base url

### PR DESCRIPTION
**Pull request by kevinasurjadi**
Update Waze deeplink base url.

Reference: https://developers.google.com/waze/deeplinks#how

### CODE REVIEW

**Comment by mattermoran** [comment]
Hey. Thanks for contributing :)
Is there any difference between using this and url scheme? Seems like website mentions that url scheme can still be used if we sure app is installed. And that we are sure because there's a check and web version wouldn't open is map is not installed.

**Comment by mattermoran** [comment]
I do plan however to add support for universal links as such for web and desktop as well some time so this would be useful later :)

**Comment by kevinasurjadi** [comment]
Absolutely true, I believe that universal link is a lot safer. Universal link makes us don't have to worry whether the app is installed or not. It's cool that you have a plan for supporting the universal link, I am looking forward to that.

**Comment by mattermoran** [comment]
There are couple of reasons I haven't made full switch to universal links. 
- Universal links generally have less "features" compared to url schemes. That's not true for all maps but for many of them. So having full feature set still requires url schemes. And some maps just don't have universal links at all. 
- Sometimes people devs want to only show installed maps because that means people prefer those maps for a reason. Especially in countries that don't use google/apple maps by default. And showing list of all the maps even not installed ones would make it hard to find you really need. 

But regardless there are ways to improve this plugin by introducing extra features enabled with universal links. Like web/desktop support as I've mentioned before. Launching web versions on mobile or opening stores to install maps, etc. 

If you would like to contribute good thing to start finding universal links for maps and available parameters etc as that the part that actually takes lots of time :)

Thanks for taking interest. Appreciate any input :)

**Comment by mattermoran** [comment]
I'm closing this as we are not yet adding support for universal links.

**Pull request closed without merging**
