### PR TITLE
Replacement of bitmap icons with SVG icons

### PR DESCRIPTION
**Pull request by shinsenter**
This can help reduce the size of the package after it is compiled.
Related to the issue #17.

@mattermoran 
TODO: SVG files are temporarily added. Replace them with better SVG files.

### CODE REVIEW

**Comment by mattermoran** [comment]
Hey @shinsenter 
It seem to work fine but the only problem I have with it is that it takes about a second before the icons actually show up. I guess that's because it needs to parse the svg files first but that's not very nice experience. I wonder if we can somehow speed it up so they show up instantly like pngs

**Comment by mattermoran** [comment]
Actually I have just tried to use svg path and pass it directly to SvgPicture.asset and in that case it seems to be instant

**Comment by mattermoran** [comment]
Seem to be fine with the `flutter_svg_provider` package as well. We might wanna roll with that but that's another extra dependency

**Comment by shinsenter** [comment]
Because you want to not change the interface of the current version, I have to workaround to change the data type of map.icon from PictureProvider to ImageProvider, so there will be a little delay when rendering the icons.

**Comment by shinsenter** [comment]
@mattermoran 
Please review again

**Comment by shinsenter** [comment]
@mattermoran 
Thank you for approval.
I think it will be faster in production mode (tested).

**Comment by mattermoran** [comment]
hey @shinsenter 
version 0.7.1 with your changes is available on pub
thanks for help!

**Comment by shinsenter** [comment]
@mattermoran
Great! Thank you

**Comment by aseef17** [comment]
Why was the intl package added as a dependancy ?

**Comment by mattermoran** [comment]
@aseef17 probably by mistake. I'm pretty sure I removed it in an actual release

**Pull request merged**
