### PR TITLE
Introduce static analysis

### PR DESCRIPTION
**Pull request by Pavel-Sulimau**
I noticed that there is no static analysis used in the repo, so I added [flutter_lints](https://pub.dev/packages/flutter_lints) and fixed the analyzer findings.

Also, updated the  Dart SDK constraint to `sdk: ">=3.0.0 <4.0.0"` and the iOS files in the example app.

### CODE REVIEW

**Comment by mattermoran** [comment]
Nice, thanks!

**Comment by akmaladib01** [comment]
is it possible to search just by name and not using coordinate? because i try using name only and it shows error

**Comment by mattermoran** [comment]
> is it possible to search just by name and not using coordinate? because i try using name only and it shows error
> 
> 

Not at the moment,no. 
I plan to add it in the next version but need to find the time

**Comment by akmaladib01** [comment]
okay understood, thank you brother.

**Pull request merged**
